# Generated by Django 5.1 on 2024-12-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extensoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('professor', models.CharField(blank=True, max_length=150, null=True)),
                ('assunto', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
